name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  ubuntu2004:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: ./docker_build_ubuntu_2004_x86_64.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: targets
  ubuntu2204:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: ./docker_build_ubuntu_2204_x86_64.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: targets
  windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: ./docker_build_windows.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: targets
